import re

class ConfigAuditor:
    def __init__(self, config_text: str):
        self.config_lines = config_text.splitlines()
        self.config_text = config_text

    def run_all_checks(self):
        return [
            self.check_password_encryption(),
            self.check_enable_secret(),
            self.check_insecure_protocols(),
            self.check_snmp_communities(),
            self.check_unshutdown_interfaces()
        ]

    @classmethod
    def generate_remediation(cls, config_text: str, rule_id: str) -> str:
        """Applies an automated remediation script to the configuration based on the rule ID."""
        lines = config_text.splitlines()
        patched_lines = []
        
        if rule_id == "SEC-001":
            for line in lines:
                if line.strip() == "no service password-encryption":
                    continue
                patched_lines.append(line)
            for i, line in enumerate(patched_lines):
                if line.startswith("hostname"):
                    patched_lines.insert(i + 1, "service password-encryption")
                    break
            else:
                patched_lines.insert(0, "service password-encryption")
                
        elif rule_id == "SEC-002":
            has_secret = any("enable secret" in l for l in lines)
            for line in lines:
                if line.startswith("enable password"):
                    if not has_secret:
                        patched_lines.append("enable secret 9$AutoGeneratedSecret123!")
                        has_secret = True
                    continue
                patched_lines.append(line)
                
        elif rule_id == "SEC-003":
            in_vty = False
            for line in lines:
                if line.strip() == "ip http server":
                    continue
                if line.startswith("line vty"):
                    in_vty = True
                    patched_lines.append(line)
                elif in_vty and (line.startswith("line") or line.startswith("interface") or line == "!"):
                    in_vty = False
                    patched_lines.append(line)
                elif in_vty and "transport input" in line:
                    patched_lines.append(" transport input ssh")
                else:
                    patched_lines.append(line)
                    
        elif rule_id == "SEC-004":
            for line in lines:
                if line.startswith("snmp-server community"):
                    patched_lines.append("snmp-server community secure_ro_string RO")
                else:
                    patched_lines.append(line)
                    
        elif rule_id == "NET-001":
            auditor = cls(config_text)
            res = auditor.check_unshutdown_interfaces()
            if res["status"] == "FAILED":
                open_ints = res["details"].replace("Active unsecured interfaces: ", "").split(", ")
                for line in lines:
                    patched_lines.append(line)
                    if line.startswith("interface"):
                        int_name = line.replace("interface ", "").strip()
                        if int_name in open_ints:
                            patched_lines.append(" shutdown")
                            patched_lines.append(" description DISABLED-BY-NETGATE")
            else:
                patched_lines = lines
        else:
            patched_lines = lines
            
        return "\n".join(patched_lines)

    def check_password_encryption(self):
        """Verify that service password-encryption is enabled."""
        has_encryption = False
        no_encryption = False
        
        for line in self.config_lines:
            cleaned = line.strip()
            if cleaned == "service password-encryption":
                has_encryption = True
            elif cleaned == "no service password-encryption":
                no_encryption = True

        if no_encryption or not has_encryption:
            return {
                "id": "SEC-001",
                "title": "Cleartext Password Storage Enabled",
                "description": "The configuration lacks global password encryption, meaning helper passwords may be stored in cleartext.",
                "severity": "MEDIUM",
                "status": "FAILED",
                "details": "Found 'no service password-encryption' or missing 'service password-encryption'.",
                "remediation_script": "service password-encryption"
            }
        
        return {
            "id": "SEC-001",
            "title": "Cleartext Password Storage Enabled",
            "description": "The configuration has global password encryption enabled.",
            "severity": "MEDIUM",
            "status": "PASSED",
            "details": "Confirmed 'service password-encryption' is present."
        }

    def check_enable_secret(self):
        """Verify that 'enable secret' is used instead of 'enable password'."""
        has_password = False
        has_secret = False
        password_lines = []

        for line in self.config_lines:
            cleaned = line.strip()
            if cleaned.startswith("enable password"):
                has_password = True
                password_lines.append(cleaned)
            elif cleaned.startswith("enable secret"):
                has_secret = True

        if has_password and not has_secret:
            return {
                "id": "SEC-002",
                "title": "Insecure Enable Password Configuration",
                "description": "An 'enable password' was found without an overriding 'enable secret'. This stores privilege passwords with weak or no encryption.",
                "severity": "HIGH",
                "status": "FAILED",
                "details": f"Found cleartext line: {', '.join(password_lines)}",
                "remediation_script": "enable secret 9$AutoGeneratedSecret123!"
            }
        elif has_password and has_secret:
            return {
                "id": "SEC-002",
                "title": "Insecure Enable Password Configuration",
                "description": "Both 'enable password' and 'enable secret' are present. While 'enable secret' takes precedence, having 'enable password' in the config is a security risk.",
                "severity": "MEDIUM",
                "status": "FAILED",
                "details": f"Found redundant cleartext line: {', '.join(password_lines)}",
                "remediation_script": "no enable password"
            }
        elif not has_secret:
            return {
                "id": "SEC-002",
                "title": "Insecure Enable Password Configuration",
                "description": "No 'enable secret' password is configured for administrative access.",
                "severity": "HIGH",
                "status": "FAILED",
                "details": "Missing 'enable secret' configuration.",
                "remediation_script": "enable secret 9$AutoGeneratedSecret123!"
            }

        return {
            "id": "SEC-002",
            "title": "Insecure Enable Password Configuration",
            "description": "Administrative password access is properly hashed using 'enable secret'.",
            "severity": "HIGH",
            "status": "PASSED",
            "details": "Confirmed 'enable secret' is present and active."
        }

    def check_insecure_protocols(self):
        """Verify that Telnet and HTTP are disabled in favor of SSH and HTTPS."""
        issues = []
        in_vty_block = False
        telnet_allowed = False

        for line in self.config_lines:
            cleaned = line.strip()
            # HTTP checks
            if cleaned == "ip http server":
                issues.append("Unencrypted HTTP administration server is active ('ip http server').")
            
            # VTY configuration block check for Telnet
            if cleaned.startswith("line vty"):
                in_vty_block = True
            elif in_vty_block and (cleaned.startswith("line") or cleaned.startswith("interface") or cleaned == "!"):
                in_vty_block = False
                
            if in_vty_block:
                if "transport input" in cleaned and ("telnet" in cleaned or "all" in cleaned):
                    telnet_allowed = True

        if telnet_allowed:
            issues.append("Insecure Telnet terminal protocol is allowed on VTY lines.")

        if issues:
            return {
                "id": "SEC-003",
                "title": "Insecure Management Protocols Enabled",
                "description": "Unencrypted administration channels (HTTP/Telnet) are allowed, exposing administrative credentials to eavesdropping.",
                "severity": "HIGH",
                "status": "FAILED",
                "details": " | ".join(issues),
                "remediation_script": "no ip http server\nline vty 0 4\ntransport input ssh"
            }

        return {
            "id": "SEC-003",
            "title": "Insecure Management Protocols Enabled",
            "description": "Management channels are secured. Unencrypted protocols (HTTP/Telnet) are blocked or disabled.",
            "severity": "HIGH",
            "status": "PASSED",
            "details": "No active HTTP server or VTY telnet inputs detected."
        }

    def check_snmp_communities(self):
        """Flag usage of default SNMP community strings 'public' or 'private'."""
        insecure_strings = []
        for line in self.config_lines:
            cleaned = line.strip()
            if cleaned.startswith("snmp-server community"):
                parts = cleaned.split()
                if len(parts) > 2:
                    community_name = parts[2]
                    if community_name.lower() in ["public", "private", "admin", "cisco", "manager"]:
                        insecure_strings.append(community_name)

        if insecure_strings:
            return {
                "id": "SEC-004",
                "title": "Default or Weak SNMP Community Strings",
                "description": "Standard read/write community strings (like 'public' or 'private') are active, allowing unauthorized network monitoring or manipulation.",
                "severity": "HIGH",
                "status": "FAILED",
                "details": f"Found weak community string(s): {', '.join(insecure_strings)}",
                "remediation_script": "snmp-server community secure_ro_string RO"
            }

        return {
            "id": "SEC-004",
            "title": "Default or Weak SNMP Community Strings",
            "description": "All SNMP community strings are configured securely or SNMP is disabled.",
            "severity": "HIGH",
            "status": "PASSED",
            "details": "No weak SNMP community strings detected."
        }

    def check_unshutdown_interfaces(self):
        """Flag physical Ethernet interfaces that are not configured with 'shutdown' and lack description."""
        open_interfaces = []
        current_interface = None
        has_shutdown = False
        has_description = False

        for line in self.config_lines:
            cleaned = line.strip()
            
            # Start of interface block
            if cleaned.startswith("interface"):
                # Evaluate the previous interface
                if current_interface and not has_shutdown and not has_description:
                    # Only flag physical ethernet/gigabit interfaces, skip loopbacks/VLANs for this audit
                    if any(x in current_interface.lower() for x in ["ethernet", "gigabit", "fastether", "ten-gig"]):
                        open_interfaces.append(current_interface)
                
                current_interface = cleaned.replace("interface ", "")
                has_shutdown = False
                has_description = False
            
            elif current_interface:
                if cleaned == "shutdown":
                    has_shutdown = True
                elif cleaned.startswith("description"):
                    has_description = True
                # End of block marker
                elif cleaned == "!" or cleaned.startswith("line") or cleaned.startswith("router"):
                    # Evaluate final line of interface block
                    if current_interface and not has_shutdown and not has_description:
                        if any(x in current_interface.lower() for x in ["ethernet", "gigabit", "fastether", "ten-gig"]):
                            open_interfaces.append(current_interface)
                    current_interface = None

        if open_interfaces:
            return {
                "id": "NET-001",
                "title": "Unsecured Physical Interfaces Active",
                "description": "Active physical interfaces are configured without 'shutdown' and lack descriptions. Unused active ports pose a physical penetration hazard.",
                "severity": "LOW",
                "status": "FAILED",
                "details": f"Active unsecured interfaces: {', '.join(open_interfaces)}",
                "remediation_script": "shutdown\ndescription DISABLED-BY-NETGATE"
            }

        return {
            "id": "NET-001",
            "title": "Unsecured Physical Interfaces Active",
            "description": "All physical ports are safely shut down, documented, or configured.",
            "severity": "LOW",
            "status": "PASSED",
            "details": "All physical interfaces are either shutdown or have documentation descriptions."
        }
